paths:
  data: data
  collections: content
  includes: layouts
  layouts: layouts
  static: static
  uploads: static/uploads
  source: ''
  archetypes: archetypes
  assets: assets
  content: content
  pages: content
  publish: public
  config: ''
collections_config:
  pages:
    path: content
    output: true
    filter: strict
    parse_branch_index: true
    icon: notes
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  docs:
    path: content/docs
    output: true
    icon: notes
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  examples:
    path: content/examples
    output: true
    icon: notes
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  guides:
    path: content/guides
    output: true
    icon: notes
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  samples:
    path: content/samples
    output: true
    icon: notes
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  users:
    path: content/users
    output: true
    icon: notes
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  tags:
    path: content/tags
    output: true
    icon: notes
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  data:
    path: data
    output: false
    icon: notes
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
_inputs: {}
_select_data: {}
_structures: {}
_editables: {}
data_config: {}
timezone: Etc/UTC
